print("Welcome to the Haiku generator!") 
print("Your haiku has to follow the rule 5/7/5.") 
print("Provide the first line of your haiku:") 
first_line = raw_input() 
print("Provide the second line of your haiku:") 
second_line = raw_input() 
print("Provide the third line of you haiku:") 
third_line = raw_input() 
print("What file would you like to write your haiku to?") 
file_name = raw_input() 
print("Done! To view your haiku, type 'cat' and the name of your file at the command line.")
